FROM rust:1-slim-bullseye AS builder
WORKDIR /fishnet
COPY . .
RUN apt update && apt install -y make g++ binutils curl
RUN RUSTFLAGS="-C target-cpu=native" cargo build --release

FROM debian:bullseye-slim
COPY --from=builder /fishnet/target/release/fishnet /fishnet
COPY docker-entrypoint.sh /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh"]
